services:
  - type: web
    name: server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URL
        value: <your-mongo-url>
      - key: ORIGIN
        value: <your-origin-url>
